### ISSUE TITLE
empty lines in train_caps.txt

### ISSUE THREAD

**Issue by lemyx** [xiaoyuan1996/GaLR#6]
Dear DR. Yuan,

Thanks for your great contributions to the community, the following researchers can push forward the topic based on your released dataset and codes.

Howerer, I found that there are empty lines in `train_caps.txt`, which I think is harmful.

Like, [train_caps.txt](https://github.com/xiaoyuan1996/GaLR/blob/ce672ce59b8890f0ceafcdabd87cee6e5e4dff0c/data/rsitmd_precomp/train_caps.txt#L9631)

It will be appreciated if any help, thank you!

**Comment by xiaoyuan1996** [comment]
Tnanks for you comments!
